---
title: "benefit_data"
author: "Ray Hunter"
date: "2023-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../common.R")
```
## do not clear environment


##IDK what this is??
```{r}
harp_mod <- stilly_bens %>% 
  filter(pop == "fall_chinook")

ben_by_scen <- harp_mod %>% 
  group_by(scenario) %>% 
    summarise(total_benefit = sum(n)) %>% 
  arrange(desc(total_benefit))


ben_by_scen %>% gt()
```

## first separate benefits into dataframes by type
```{r}
flood_bens<-stilly_bens %>% filter(scenario=="Floodplain" & pop=="fall_chinook")
elj_bens<-stilly_bens %>% filter(scenario=="Wood" & pop=="fall_chinook")  
rp_bens<-stilly_bens %>% filter(scenario=="Shade" & pop=="fall_chinook")
```

## join the benefit dataframes with the cost dataframes
```{r}
##need to load each cost rmd before these will work bc of the environment clearing
#floodplain
flood_cost_ben <- full_join(stilly_subbasin_cost, flood_bens, by = c("noaa_subba" = "subbasin"))
#ELJ
##need to change this out for the inflation adjusted cost **********
elj_cost_ben <- full_join(elj_no_inf_cost_sf, elj_bens, by = c("noaa_subba" = "subbasin"))

#RP
```

## calculate cost benefit ratio
Calculate this by dividing the average cost by number of fish increase
Should we also do by perc_change?
```{r}
#floodplain
##need to manipulate values so that when n=0 (zero fish are benefitted) the ratio is 0, also I need the value to be NA when avg_cost is NA
##logically the value should never be NA (that means we didn't calculate a price for a basin with benefits)
flood_cost_ben <- flood_cost_ben %>%
  mutate(ratio = NA) %>% 
  mutate(ratio = ifelse(!is.na(avg_cost), avg_cost / n, NA))
flood_cost_ben$ratio <- replace(flood_cost_ben$ratio, is.infinite(flood_cost_ben$ratio), 0)
flood_cost_ben <- flood_cost_ben %>%
  mutate(ratio_log = if_else(!is.na(ratio) & ratio != 0, log(ratio), NA_real_))

#ELJ
elj_cost_ben$ratio<-elj_cost_ben$avg_cost/elj_cost_ben$n
#RP
```

## floodplain map
```{r}
#regular scale
 ggplot() +
  geom_sf(data = subs_stl, aes()) +
  geom_sf(data = flood_cost_ben, aes(fill = ratio)) +
  # scale_fill_viridis_b(breaks = c(0, 45000000, 90000000),
  #                      labels = c("0 Million", "45 Million", "90 Million")) +
  geom_sf(data = flow_stl, color = "blue", alpha = .3) +
  # scale_fill_continuous() +
  theme_minimal()+
  labs(fill="Cost Benefit Ratio")

#log scale
 ggplot() +
  geom_sf(data = subs_stl, aes()) +
  geom_sf(data = flood_cost_ben, aes(fill = ratio_log)) +
  # scale_fill_viridis_b(breaks = c(0, 45000000, 90000000),
  #                      labels = c("0 Million", "45 Million", "90 Million")) +
  geom_sf(data = flow_stl, color = "blue", alpha = .3) +
  # scale_fill_continuous() +
  theme_minimal()+
  labs(fill="Cost Benefit Ratio")
```

## ELJ map
```{r}
ggplot() +
  geom_sf(data = subs_stl, aes()) +
  geom_sf(data = elj_cost_ben, aes(color = ratio)) + #use color, not fill bc line
  # scale_color_viridis_c(breaks = c(0, 1500, 4500, 1), option = "B")
  theme_minimal()+
  labs(fill="Average Cost ($)")
```

## RP map
```{r}

```

