<<<<<<< HEAD
---
title: "cost_data"
author: "Meghan Roberts"
date: "2023-09-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(janitor)
library(tidyverse)
library(ggplot2)
```

```{r}
## Import Cost data
cost_project<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Project.csv"))
cost_land_type<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Acquisition_Land_Type.csv"))
cost_metrics<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Metrics.csv"))
cost_costm<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Cost_Metrics.csv"))
cost_ac_metrics<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Acquisition_Metrics.csv"))
cost_worksite<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Worksite.csv"))
```

```{r}
## Import Environmental Data (HARP)

metric_sum <- cost_metrics %>% 
  group_by(MetricIdentifier) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))


ggplot(cost_metrics, aes(x = MetricIdentifier)) +
  geom_bar()
```

=======
---
title: "cost_data"
author: "Meghan Roberts"
date: "2023-09-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(janitor)
library(tidyverse)
library(ggplot2)
library(xlsx)
```

```{r}
## Import Cost data
cost_project<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Project.csv"))
cost_land_type<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Acquisition_Land_Type.csv"))
cost_metrics<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Metrics.csv"))
cost_costm<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Cost_Metrics.csv"))
cost_ac_metrics<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Acquisition_Metrics.csv"))
cost_worksite<-read_csv(here("data", "SRP_Cost_Data", "NOAA_Stilly_Snohomish_Worksite.csv"))
```

```{r}
## Import Environmental Data (HARP)
metrics<-read_csv(here("data", "SRP_metrics.csv")) %>% clean_names()
metric_identifier<-as.data.frame(unique(metrics$metric_identifier))
write.xlxs(metric_identifier, "unique_identifiers")
```

>>>>>>> f73aab1167c56f2fa7758fe622c1e3a67eccf5e6
