---
title: "cost_rp"
author: "Ray Hunter"
date: "2023-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include=FALSE, message = FALSE, error = FALSE)


#clearing environment
rm(list = ls())

#sourcing data
source("../common.R")
```



### 1) IMPACT OF SITE ACCESSIBILITY AND MATERIALS ON COSTS
```{r}
# use function from engineered log jams 
# site accessability (distance to nearest road ) and materials (stream bank size )

```



### 2) COST OF RIPARIAN PLANTING PROJECTS ($/acre)
```{r}
## matrix with levels of site preparation ( average slope ) and output from materials/accessibility 
# need to measure the average slope around a stream within 50m 
```

#### 2.1) 

```{r}
                     
# importing elevation raster data
# Data: https://gis.ess.washington.edu/data/raster/tenmeter/byquad/info.html


# listing the dem elevation files 
elev_list <- list.files(path = "/Users/rayhunter/Desktop/GP/gp_anadromites/data/elevation", "dem$", 
                   full.names = TRUE)

#  rasterizing elevation dem files and storing them in a collection 
elev_list_rast <- sprc(lapply(elev_list, rast))

# combining rasters into 1 mosaic
elev_mos <- mosaic(elev_list_rast)

#calculating slope from elevation data
full_slope <- terrain(x = elev_mos, v = "slope", unit = "degrees")
plot(full_slope)

# projecting NAD83 (which is more accurate and used by the NOAA files) onto raster data (originally using NAD27)  
full_slope <- project(full_slope, "EPSG:26910")

# writeLines(crs(flow_buff))
# writeLines(crs(full_slope))

# creating a 50m buffer around stream edges
flow_buff <- st_buffer(flow_stl, dist = 50, endCapStyle = "FLAT")

# cropping and masking slope raster data to stream buffer
crop_rast <- crop(full_slope, flow_buff, mask = TRUE)
plot(crop_rast)

#extract mean 
extract <- extract(crop_rast, flow_buff, fun = mean)

#joining
flow_buff <- flow_buff %>% 
  mutate(avg_slope = extract$slope)



hist(flow_buff$avg_slope)

# calculate the average slope in degrees w/ in a 50m buffer of each reach 

# buff_rast <- rasterize(vect(flow_buff),
#                       crop_rast,
#                       field = "noaaid")
# 
# slope_zonal <- zonal(crop_rast,
#                   buff_rast,
#                   fun = "mean",
#                   na.rm = TRUE)
#
# avg_slope <- left_join(flow_buff,
#                          slope_zonal, 
#                        by = "noaaid") %>% 
#   rename(avg_slope = slope.y)

# #trying to figure out why there are NA values in small buffer polygons 
# 
# avg_slope2 <- avg_slope %>% 
#   filter(is.na(avg_slope))






```



```{r}
# # plotting raster as a df so that it can be plotted in ggplot 
# # computationally expensive, so only run if needed 

# elev_mos_df <- as.data.frame(elev_mos, xy = TRUE)



ggplot() +
  # # ggplotting raster layer (only run if needed)
  # geom_raster(data = elev_mos_df, aes(x = x, y = y, fill = q525)) +
  # geom_sf(data = flow_buff, color = "red") +
  geom_sf(data = flow_buff, aes(col = avg_slope)) +
  scale_color_viridis_c() +
  # geom_sf(data = flow_stl, color = "red") +
  
  # geom_sf(data = flood_sf, aes(fill = Period)) + 
  theme_minimal() 
  # labs(title = "Stillaguamish Basin", color = "Stream type", fill = "Wetland Status")
```






