---
title: "cost_elj"
author: "Meghan Roberts"
date: "2023-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#clearing environment
rm(list = ls())
#sourcing data
source("../common.R")
```

## LOADING IN THE ROAD DATA/GETTING IT SMALL ENOUGH TO GO ON GITHUB
```{r}
#print(roads)
## no need to run this ever again
# roads <-roads %>% select("OBJECTID", "NAME")
# st_write(roads, here("data/Washington_data/WA_roads_thin.gpkg"))
```

## FIND THE NEAREST ROAD TO EACH STREAM REACH
```{r}
# Create sf objects
sf_roads <- st_as_sf(roads_stl)
sf_streamreaches <- st_as_sf(flow_stl, coords = c("lon", "lat"), crs = 4326)

# Check and match CRS
if (!identical(st_crs(sf_roads), st_crs(sf_streamreaches))) {
  sf_roads <- st_transform(sf_roads, st_crs(sf_streamreaches))
}
# Find the distance from each stream to the nearest road
distances <- st_distance(sf_streamreaches, sf_roads)

# Extract the minimum distance for each stream reach
min_distances <- apply(distances, 1, min)

# Add the distances to the original data.frame
flow_stl$distance_to_nearest_road_m <- min_distances
flow_stl$distance_to_nearest_road_mi <- flow_stl$distance_to_nearest_road_m *0.000621371

# Print the resulting data.frame
print(flow_stl)

# Check the CRS of sf_streamreaches
crs_streamreaches <- st_crs(flow_stl)
print(crs_streamreaches$units)
```

