---
title: "final_figures"
author: "Ray Hunter"
date: "2024-01-17"
output: 
  html_document:
    code_folding: "hide"
---
## Preliminary Results {.tabset}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(sf)
library(terra)
library(ggspatial)
# library(tmap)
library(here)
library(janitor)
library(ggplot2)
library(kableExtra)
library(magrittr)
library(knitr)
library(basemaps)
library(ggmap)
library(patchwork)
library(spData)

#sourcing data
source("../common.R")
source("functions.R")

# color themes 
custom_colors <- c("rp" = "#03045E",
                   # "#1F271B",
                   "elj" = "#19647E", 
                   "floodplain" = "#28AFB0")
```


# Data wrangling 

```{r}
#reading in data 

#floodplain habitat
floodplain<-read_sf(here("data", "final_dfs", "fp_costs.gpkg")) %>% 
  select(-c("scenario", "subbasin_num")) %>% 
  mutate(restoration_type = "floodplain")

#engineered log jams 
elj<-read_sf(here("data", "final_dfs", "elj_costs.gpkg")) %>% 
  mutate(restoration_type = "elj")

#riparian planting 
rp <- read_sf(here("data", "final_dfs", "rp_costs.gpkg")) %>% 
  select(-scenario) %>% 
  mutate(restoration_type = "rp")

#creating a master df
all_cost_benefit <- rbind(floodplain, elj)
all_cost_benefit <- rbind(all_cost_benefit, rp) %>% 
  #cleaning names
  mutate(subbasin_name = str_replace_all(noaa_subba, "_", " "),
         subbasin_name = str_replace_all(subbasin_name, "Stillaguamish", ""),
         subbasin_name = str_replace_all(subbasin_name, "mainstem", "Mainstem")
  ) 

```



# CB Maps

```{r}

####### google basemap ###########

# api key
ggmap::register_google(key = "AIzaSyAMlAe4fbAxjFToWnpW-28exZtSUC6bXL8")
api_key <- "AIzaSyAMlAe4fbAxjFToWnpW-28exZtSUC6bXL8"

# making google map base map 
basemap <- ggmap::get_googlemap(
  center = c(lon = -121.9, lat = 48.25),
  zoom = 9,
  maptype = "satellite",
  extent = "panel",
  source = "google",
  key = api_key)

###------------ Making a map --------------------

# Chaning crs to match basemap 
subs_4326 <- subs_stl %>% 
  st_transform(4326)

# filtering map data 
map_data <- all_cost_benefit %>% 
  filter(pop == "fall_chinook",
         cb_ratio > 0) %>% 
  st_transform(crs = st_crs(subs_4326))


# creating and saving CB maps 

# Floodplain -------------------------------------------------
fp_map <- cb_map_fun(rest_type = "floodplain",
                   breaks = c(.3, .6, .9, 1.2, 1.5, 1.8), 
                   break_labs = c("$30,000",
                                  "$60,000",
                                  "$90,000",
                                  "$120,000",
                                  "$150,000",
                                  "$180,000"),
                   title = "Floodplain"
)

# save  rp map 
ggsave("../final_prods/figures/cb_maps/fp_map.jpeg", plot = fp_map, device = "jpeg", width = 8, height = 6, units = "in")

# Engineered log jam -------------------------------------------------
elj_map <- cb_map_fun(rest_type = "elj",  
                   breaks = c(.15, .3, .45, .6, .75, .9), 
                   break_labs = c("$15,000",
                                  "$30,000",
                                  "$45,000",
                                  "$60,000",
                                  "$75,000",
                                  "$90,000"),
                   title = "Engineered Log Jam"
)

# save  rp map 
ggsave("../final_prods/figures/cb_maps/elj_map.jpeg", plot = elj_map, device = "jpeg", width = 8, height = 6, units = "in")

# RP -------------------------------------------------
rp_map <- cb_map_fun(rest_type = "rp", 
                   breaks = c(.5, 1, 1.5, 2, 2.5, 3), 
                   break_labs = c("$50,000",
                                  "$100,000",
                                  "$150,000",
                                  "$200,000",
                                  "$250,000",
                                  "$300,000"),
                   title = "Riparian Planting"
)

# save  rp map 
ggsave("../final_prods/figures/cb_maps/rp_map.jpeg", plot = rp_map, device = "jpeg", width = 8, height = 6, units = "in")
```






# Puget Sound Basin map 
```{r}
#data link 

# https://geo.wa.gov/datasets/de1373e9f5394e5284660c939c038689/explore?location=47.575830%2C-122.409706%2C9.34

# --------------reading in basins data -----------------------------------------------
all_basins <- st_read(here("data", "basins", "WBDHU08.shp")) %>% 
  clean_names() %>% 
  select(name,area_acres, huc8, geometry) %>%
  filter(!name %in% c("Puget Sound")) %>% 
  st_transform(crs = st_crs(subs_4326))

#selecting basins for ps map
ps_basins <- all_basins %>% 
  filter(name %in% c("Nooksack", "Upper Skagit", "Lower Skagit", "Stillaguamish", "Snohomish", "Skykomish", "Snoqualmie", "Lake Washington", "Duwamish", "Puyallup", "Nisqually", "Deschutes", "Upper Chehalis", "Lower Chehalis", "Skokomish", "Hood Canal", "Dungeness-Elwha", "Ho-Quillayute", "Crescent-Hoko", "Sauk", "Upper Skagit"))

# ---------------centroids for labeling------------------------------------------

# making centroids
ps_cents <- st_centroid(ps_basins)

# Adjust centroids for labeling the values that overlap in geom_sf_label
ps_cents_adjusted <- ps_cents

#lake washington centroid adjustment 
ps_cents_adjusted$geometry[ps_cents_adjusted$name == "Lake Washington"] <- 
  ps_cents_adjusted$geometry[ps_cents_adjusted$name == "Lake Washington"] + c(-0.1, .06) 

#upper chehalis centroid adjustment 
ps_cents_adjusted$geometry[ps_cents_adjusted$name == "Upper Chehalis"] <- 
  ps_cents_adjusted$geometry[ps_cents_adjusted$name == "Upper Chehalis"] + c(0.01, .17) 

#upper skagit centroid adjustment 
ps_cents_adjusted$geometry[ps_cents_adjusted$name == "Upper Skagit"] <- 
  ps_cents_adjusted$geometry[ps_cents_adjusted$name == "Upper Skagit"] + c(-.23, -0.1)

#sauk centroid adjustment 
ps_cents_adjusted$geometry[ps_cents_adjusted$name == "Sauk"] <- 
  ps_cents_adjusted$geometry[ps_cents_adjusted$name == "Sauk"] + c(-0.15, 0)

# ------------------ making a basemap ---------------------------------------------


# creating a base map of PS with google maps
ps_basemap <- ggmap::get_googlemap(
  center = c(lon = -123, lat = 47.85),
  zoom = 8,
  maptype = "satellite",
  extent = "panel",
  source = "google",
  key = api_key)
# ------------------ making a PS map ---------------------------------------------

# creating an area map of PS with basins 
ps_basin_map <- ggmap(ps_basemap) +
  geom_sf(data = ps_basins,
          fill = ifelse(ps_basins$name == "Stillaguamish", "cyan3", "white"),
          alpha = ifelse(ps_basins$name == "Stillaguamish", 0.8, 0.4),
          color = "black",
          inherit.aes = FALSE) +
  
  # labeling centroids 
  geom_sf_label(data = ps_cents_adjusted, aes(label = name),
                size = 2, label.padding = unit(0.2, "lines"),
                inherit.aes = FALSE) +
  
  theme_minimal() +
  labs(x = "",
       y = "",
       title = "Stillaguamish River Basin in the Puget Sound") +
  
  #axes
  scale_y_continuous(limits = c(46.8, 49), expand = c(0, 0)) +
  
  # north arrow
  ggspatial::annotation_north_arrow(height = unit(1.4, "cm"), 
                                    width = unit(1, "cm"), 
                                    pad_x = unit(.45, "cm"), 
                                    pad_y = unit(1.1, "cm"),
                                    text_col = "white",
                                    which_north = "true") +
  
  # white rectangle behind scale
  annotation_custom(grob = grid::rectGrob(
    x = unit(2.4, "cm"),
    y = unit(.35, "cm"),
    width = unit(4.7, "cm"), 
    height = unit(.4, "cm"),
    gp = grid::gpar(fill = "white")
    # gp = grid::gpar(col = NA)
  )) +
  # scale 
  ggspatial::annotation_scale(height = unit(0.2, "cm"),
                              bar_cols = c("black", "white"),
                              text_cex = .8
  ) 
# saving figure 
ggsave("../final_prods/figures/ps_maps/ps_basin_map.jpeg", plot = ps_basin_map, device = "jpeg", width = 8, height = 6, units = "in")


```


# Inset map 
```{r}

# PNW bounding box 
# Create a data frame with the bounding box coordinates
ps_bbox_coords <- st_polygon(list(
  matrix(
    c(-124.7, 46.8, -124.7, 49, -121, 49, -121, 46.8, -124.7, 46.8),
    ncol = 2, byrow = TRUE)))

# making the box a simple features object 
ps_bbox <- st_sfc(ps_bbox_coords, crs = 4326)


# PNW world base map of PS with google maps
pnw_basemap <- ggmap::get_googlemap(
  center = c(lon = -123, lat = 47.85),
  zoom = 5,
  maptype = "terrain",
  extent = "panel",
  source = "google",
  key = api_key)

ggmap(pnw_basemap)


# --------------aligning CRS with workaround -----------------------------------------


# Transform nc to EPSG 3857 (Pseudo-Mercator, what Google uses)
ps_bbox_3857 <- st_transform(ps_bbox, 3857)

# Define a function to fix the bbox to be in EPSG:3857
  # this is a bug in the ggmap packages and is a workaround 
ggmap_bbox <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 

  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}


pnw_basemap_test <- ggmap_bbox(pnw_basemap)

# -----------------------------------------------------------------------



#making an inset map of PNW with PS filled in red  
inset <- ggmap(pnw_basemap_test) +
  coord_sf(crs = st_crs(3857)) + # force the ggplot2 map to be in 3857
  geom_sf(data = ps_bbox_3857, 
          fill = "red", alpha = 0.5,
          inherit.aes = FALSE) +
  labs(x = "",
       y = "") +
  theme_minimal() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

inset

#save item 
ggsave("../final_prods/figures/ps_maps/inset.jpeg", plot = inset, device = "jpeg", width = 8, height = 6, units = "in")

```


# Final PS Map 
```{r}
# combine PS and Inset map 
final_ps_map <- ps_basin_map +
  patchwork::inset_element(inset, left = -0.4, bottom = .2, right = .65, top = .55)

#save item 
ggsave("../final_prods/figures/ps_maps/final_ps_map.jpeg", plot = final_ps_map, device = "jpeg", width = 8, height = 6, units = "in")


```


# DUMB BELL CHARTS

```{r}
#---------------- creating/saving dumbbell charts
# function in "functions.R"

# floodplain
fp_dumb_bell <- cost_graph_fun(all_cost_benefit, "floodplain", "Floodplain")

ggsave("../final_prods/figures/total_cost/fp_dumb_bell.jpeg", plot = fp_dumb_bell, device = "jpeg", width = 8, height = 6, units = "in")

# elj
elj_dumb_bell <- cost_graph_fun(all_cost_benefit, "elj", "Engineered Log Jam")
ggsave("../final_prods/figures/total_cost/elj_dumb_bell.jpeg", plot = elj_dumb_bell, device = "jpeg", width = 8, height = 6, units = "in")

# rp
rp_dumb_bell <- cost_graph_fun(all_cost_benefit, "rp", "Riparian Planting")

ggsave("../final_prods/figures/total_cost/rp_dumb_bell.jpeg", plot = rp_dumb_bell, device = "jpeg", width = 8, height = 6, units = "in")
```


# TABLES 

```{r}
#---------------- creating/saving tables 


# fp table
floodplain_table <- summary_table_builder("floodplain")

floodplain_table %>% 
  save_kable(file = here("final_prods","tables","floodplain_kable.png"), zoom = 4)

#elj table 
elj_table <- summary_table_builder("elj")

elj_table %>% 
  save_kable(file = here("final_prods","tables","elj_kable.png"), zoom = 4)

# rp table
rp_table <- summary_table_builder("rp")

rp_table %>% 
  save_kable(file = here("final_prods","tables","rp_kable.png"), zoom = 4)


# Top 20 

  top20 <- all_cost_benefit %>% 
    filter(pop == "fall_chinook") %>% 
    arrange(cb_ratio) %>% 
    slice(1:20) %>% 
    transmute("Subbasin Name" = subbasin_name,
              "Restoration Type" = restoration_type,
              "Lower Cost" = paste("$", format(round(total_lower_cost), big.mark = ",")),
              # "Lower Cost" = paste("$", format(round(total_lower_cost), big.mark = ",")),
              "Upper Cost" = paste("$", format(round(total_upper_cost), big.mark = ",")),
              "Average Cost" = paste("$", format(round(total_avg_cost), big.mark = ",")),
              "Spawners" = round(n_diff, digits = 2), 
              "CB Ratio" = paste("$", format(round(cb_ratio, digits = 2), big.mark = ","))) %>% 
    st_drop_geometry() %>% 
    as.data.frame() %>% 
    kable() %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed")) 
  
  top20 %>% 
  save_kable(file = here("final_prods","tables","top20.png"), zoom = 4)

```







### Spawner Bar Chart
```{r}

#creating a bar chart with spawners by action and subbasin

spawner_barchart <- all_cost_benefit %>% 
  filter(pop == "fall_chinook") %>% 
  mutate(subbasin_name = fct_reorder(subbasin_name, n_diff, .fun = sum),
         restoration_type = factor(restoration_type,
                                   levels = c( "rp", "elj", "floodplain"))) %>% 
  group_by(subbasin_name) %>% 
  # creating a column to identify where the labels of the n_diff will go on the bar chart for each restoration type in each subbasin
  mutate(label_y = cumsum(n_diff) - .5 * n_diff) %>% 
  
  ggplot(aes(x = subbasin_name, 
             y = n_diff, fill = restoration_type)) +
  theme_minimal() +
  geom_col() +
  labs(fill = "Restoration Type", 
       x = "", 
       y = "# Chinook Spawners",
       title = "Modeled Annual Chinook Spawner Increases",
       subtitle = "by subbasin and restoration action",
       caption = "Data Source: Beechie, T. J., Goodman, A., Stefankiv, O., Timpane-Padgham, B., & Lowe, M. (2023). \n Habitat Assessment and Restoration Planning (HARP) Model for the Snohomish and Stillaguamish \n River Basins (noaa:48860).") +
  coord_flip() +
  scale_fill_manual(values = custom_colors,
                    labels = c("Riparian Planting",
                               "Engineered Log Jam",
                               "Floodplain"),
                    guide = guide_legend(reverse = TRUE)) +
  geom_text(aes(y = label_y, label = round(n_diff)), color = "white", alpha = 0.5) +
  
  # pushing y axis labels to edhe of data 
  scale_y_continuous(expand = c(0,0)) +
  
  # scale_y_continuous(limits = c(0, 85)) +
  theme(
    #axes
    axis.text = element_text(size = 10),
    axis.title.x = element_text(margin = margin(t = 12, r = 0, b = 30, l = 20), size = 12),
    #legend
    legend.position = c(0.5, -0.175),
    legend.direction = "horizontal",
    legend.title = element_blank(),
    # legend.box.background = element_rect(color = "grey"))
    # titles
    plot.title = element_text(hjust = 0, vjust = 1.8, size = 16),
    plot.subtitle = element_text(hjust = 0, vjust = 2.2),
    plot.caption = element_text(face = "italic", size = 6),
    # gridlines
    panel.grid.major.y  = element_blank(),
    panel.grid.minor.x  = element_blank()
  ) 

spawner_barchart

ggsave("../final_prods/figures/spawner_barchart.jpeg", plot = spawner_barchart, device = "jpeg", width = 8, height = 6, units = "in")

```







# Floodplain Breakdown 
```{r}
# wrangling floodplain area data frame
fp_area_subbasin <- read_csv(here("data", "final_dfs", "fp_area_subbasin.csv")) %>% 
  #creating a column with pretty subbasin names
mutate(subbasin_name = str_replace_all(noaa_subba, "_", " "),
       subbasin_name = str_replace_all(subbasin_name, "Stillaguamish", ""),
       subbasin_name = str_replace_all(subbasin_name, "mainstem", "Mainstem"), 
       hab_unit = str_replace_all(hab_unit, "side_channel", "Side Channel")) %>% 
filter(subbasin_name %in% unique(all_cost_benefit$subbasin_name))

# plotting side channel 
fp_area_subbasin %>% 
  filter(hab_unit == "Side Channel") %>% 
ggplot(aes(x = fct_reorder(subbasin_name, total_area_ha), 
                             y = total_area_ha)) +
  geom_bar(stat = "identity",
           fill = "#03045E") +
  theme_minimal() +
  theme(
    axis.title.y = element_text(margin = margin(r = 10)),
    axis.title.x = element_text(margin = margin(t = 10))
  ) +
  
  labs( x="Subbasin Name", y="Total Side Channel Area (HA)")+
  coord_flip() 

# ggsave(here("final_prods", "figures", "sidechannel_area_subbasin.jpg"), sc_area)

# plotting Marsh 
fp_area_subbasin %>% 
  filter(hab_unit == "Marsh") %>% 
ggplot(aes(x = fct_reorder(subbasin_name, total_area_ha), 
                             y = total_area_ha)) +
  geom_bar(stat = "identity",
           fill = "#03045E") +
  theme_minimal() +
    theme(
    axis.title.y = element_text(margin = margin(r = 10)),
    axis.title.x = element_text(margin = margin(t = 10))
  ) +
  labs( x="Subbasin Name", y="Total Side Channel Area (HA)")+
  coord_flip() 


# plotting Pond 
fp_area_subbasin %>% 
  filter(hab_unit == "Pond") %>% 
ggplot(aes(x = fct_reorder(subbasin_name, total_area_ha), 
                             y = total_area_ha)) +
  geom_bar(stat = "identity",
           fill = "#03045E") +
  theme_minimal() +
    theme(
    axis.title.y = element_text(margin = margin(r = 10)),
    axis.title.x = element_text(margin = margin(t = 10))
  ) +
  labs( x="Subbasin Name", y="Total Side Channel Area (HA)")+
  coord_flip() 
  
```


# cost effectiveness vs spawners
```{r}
options(scipen = 9999)

cb_spawner_scatter <- all_cost_benefit %>% 
  filter(pop == "fall_chinook",
         cb_ratio < 400000) %>% 
  mutate(restoration_type = factor(restoration_type,
                            levels = c( "floodplain", "elj", "rp"))) %>%
  
  ggplot(aes(x = n_diff, y = cb_ratio, color = restoration_type)) +
  geom_point(size = 3,
             alpha = .9
            ) +
  labs( x = "# Chinook Spawners",
        y = "Cost Effectiveness Ratio",
        color = "Restoration Type") +
  theme_minimal() +

  scale_color_manual(values = custom_colors,
                    labels = c("Floodplain",
                               "Engineered Log Jam",
                               "Riparian Planting")) +
  
   ylim(ymin = 0, ymax = 500000) +
  
  scale_y_continuous(labels = scales::label_currency(accuracy = 1, scale = 0.001, suffix = "k")) +
 
  theme(
    legend.position = c(.8051, .713),
    legend.box.background = element_rect(color = "grey2",
                                         fill = "white"),
    axis.title.y = element_text(margin = margin(r = 10)),
    axis.title.x = element_text(margin = margin(t = 10))
    
  ) +
  
  guides(size = "none", color = "legend")


ggsave("../final_prods/figures/cb_spawner_scatter.jpeg", plot = cb_spawner_scatter, device = "jpeg", width = 8, height = 6, units = "in")
```


#checking the barriers map (not for final)
```{r}
ggplot()+
  geom_sf(data=stl_barriers, aes(color=prcnt__))+
  geom_sf(data=flow_stl)
#currently they are in different crs so the map looks weird
```












