---
title: "maps"
author: "Ray Hunter"
date: "2023-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(ggspatial)
library(tmap)
library(leaflet)


#sourcing data
source("../common.R")
```


```{r}
#read in flow data 
flow_df <- fortify(flow_stl)




```

```{r}
#compress into x and y (plotting hates z)
flow_sf <- st_zm(flow_stl, what = "ZM")
flood_sf <- st_zm(flood_stl, what = "ZM")
subs_sf <- st_zm(subs_stl, what = "ZM")
```


### Flow Map 
```{r}



ggplot() +
  geom_sf(data = subs_stl, aes()) +
  geom_sf(data = flow_sf, aes(color = Habitat)) +
  geom_sf(data = flood_sf, aes(fill = Period)) + 
  theme_minimal() +
  labs(title = "Stillaguamish Basin", color = "Stream type", fill = "Wetland Status")
```


## Flood Map 
```{r}
ggplot() + 
  geom_sf(data = flood_df, aes(fill = "blue")) + 
  theme_minimal()



```

# interactive 
```{r}


  leaflet(flood_sf) %>%
  addTiles() %>%
  addPolygons()
```


















